name: Docker Build

on:
  pull_request:
    branches: ['master']
    paths: 
      - '**.py'
      - 'Dockerfile'
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t stable-diffusion:pr .

